// JMA UK Projects 2002–2023
// Source: jaffnamuslimuk.org official project reports
// All amounts verified from original site pages
// Charity No. 1143032

export type ProjectCategory =
  | "education"
  | "medical"
  | "housing"
  | "employment"
  | "water"
  | "religious"
  | "disaster"
  | "sports"
  | "welfare"
  | "disability"
  | "admin";

export interface Project {
  month: string;
  type: ProjectCategory;
  label: string;
  location: string;
  gbp: number;
  lkr: number;
}

export interface YearGroup {
  id: string;
  label: string;
  projects: Project[];
}

export const PROJECTS: YearGroup[] = [
  {
    id: "y2002",
    label: "2002–2011",
    projects: [
      { month: "Jan 2002", type: "welfare", label: "Janaza Support", location: "London, UK", gbp: 300, lkr: 0 },
      { month: "Jul 2002", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 150000 },
      { month: "Apr 2003", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 110000 },
      { month: "Jan 2004", type: "employment", label: "Employment Support", location: "Sri Lanka", gbp: 0, lkr: 110000 },
      { month: "Feb 2004", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "Mar 2004", type: "welfare", label: "Wedding Support", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "May 2004", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 100000 },
      { month: "May 2004", type: "employment", label: "Employment Support", location: "Sri Lanka", gbp: 0, lkr: 20000 },
      { month: "May 2004", type: "welfare", label: "Wedding Support", location: "Sri Lanka", gbp: 0, lkr: 85000 },
      { month: "Jun 2004", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 36000 },
      { month: "Nov 2004", type: "admin", label: "Eid Gathering", location: "UK", gbp: 1224, lkr: 0 },
      { month: "Dec 2004", type: "disaster", label: "Emergency Disaster", location: "Sri Lanka", gbp: 0, lkr: 150000 },
      { month: "Dec 2004", type: "disaster", label: "Emergency Disaster / Tsunami Relief", location: "Sri Lanka", gbp: 0, lkr: 252000 },
      { month: "Apr 2005", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 96000 },
      { month: "May 2005", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 50000 },
      { month: "May 2006", type: "housing", label: "Osmaniya Garden Land Purchase", location: "Thilliyadi, Sri Lanka", gbp: 0, lkr: 1200000 },
      { month: "Jan 2008", type: "admin", label: "Eid Gathering", location: "UK", gbp: 0, lkr: 975 },
      { month: "Jan 2008", type: "education", label: "Education Support", location: "Jaffna / Puttalam", gbp: 0, lkr: 60000 },
      { month: "Oct 2008", type: "admin", label: "Eid Gathering", location: "UK", gbp: 1766.76, lkr: 0 },
      { month: "Jan 2009", type: "medical", label: "Medical & Health", location: "Jaffna / Puttalam", gbp: 0, lkr: 60000 },
      { month: "Jun 2009", type: "sports", label: "Sports", location: "Jaffna", gbp: 0, lkr: 50000 },
      { month: "Jun 2010", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 145000 },
      { month: "Jun 2010", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 48000 },
      { month: "Jan 2011", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 120000 },
      { month: "Jan 2011", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "Jan 2011", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 15000 },
      { month: "Jan 2011", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 87000 },
      { month: "Jan 2011", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 20000 },
      { month: "Jan 2011", type: "welfare", label: "Orphans & Elders Support", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "Jan 2011", type: "housing", label: "Housing & Sanitation", location: "Sri Lanka", gbp: 0, lkr: 104500 },
      { month: "Jan 2011", type: "admin", label: "JMA Website Development", location: "UK", gbp: 450, lkr: 0 },
      { month: "Jan 2011", type: "admin", label: "Charity Registration Expense", location: "UK", gbp: 375, lkr: 0 },
      { month: "Jan 2011", type: "religious", label: "Ifthar", location: "Sri Lanka", gbp: 0, lkr: 105400 },
      { month: "Aug 2011", type: "religious", label: "Fitra", location: "Sri Lanka", gbp: 0, lkr: 170600 },
      { month: "Nov 2011", type: "admin", label: "Eid Gathering (2011/2012)", location: "UK", gbp: 6454.18, lkr: 0 },
      { month: "Nov 2011", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 188000 },
    ],
  },
  {
    id: "y2012",
    label: "2012–2014",
    projects: [
      { month: "2012", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 120000 },
      { month: "2012", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 100000 },
      { month: "2012", type: "employment", label: "Employment Support", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "2012", type: "welfare", label: "Funeral Service Support", location: "Sri Lanka", gbp: 0, lkr: 23500 },
      { month: "2012", type: "disability", label: "Wheelchair", location: "Sri Lanka", gbp: 0, lkr: 18000 },
      { month: "2012", type: "housing", label: "Housing & Sanitation", location: "Sri Lanka", gbp: 0, lkr: 104500 },
      { month: "2012", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 30000 },
      { month: "2012", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 72000 },
      { month: "2012", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 108000 },
      { month: "2012", type: "religious", label: "Fitra", location: "Sri Lanka", gbp: 0, lkr: 297250 },
      { month: "2012", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 205000 },
      { month: "2013", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 25000 },
      { month: "2013", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 25000 },
      { month: "2013", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "2013", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "2013", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 100000 },
      { month: "2013", type: "disability", label: "Wheelchair", location: "Sri Lanka", gbp: 0, lkr: 39600 },
      { month: "2013", type: "disability", label: "Wheelchair", location: "Sri Lanka", gbp: 0, lkr: 9900 },
      { month: "2013", type: "disability", label: "Wheelchair", location: "Sri Lanka", gbp: 0, lkr: 19400 },
      { month: "2013", type: "water", label: "Tube Well", location: "Sri Lanka", gbp: 0, lkr: 70000 },
      { month: "2013", type: "housing", label: "Housing & Sanitation", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "2013", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 47000 },
      { month: "2013", type: "employment", label: "Employment Support", location: "Sri Lanka", gbp: 0, lkr: 30000 },
      { month: "2013", type: "sports", label: "Sports", location: "Sri Lanka", gbp: 0, lkr: 10000 },
      { month: "2013", type: "welfare", label: "Family Support", location: "Sri Lanka", gbp: 0, lkr: 60000 },
      { month: "2013", type: "religious", label: "Fitra", location: "Sri Lanka", gbp: 0, lkr: 590000 },
      { month: "2013", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 440000 },
      { month: "2014", type: "disability", label: "Wheelchair Distribution", location: "Sri Lanka", gbp: 0, lkr: 0 },
      { month: "2014", type: "education", label: "Education (Multiple)", location: "Sri Lanka", gbp: 0, lkr: 0 },
      { month: "2014", type: "employment", label: "Employment Support", location: "Sri Lanka", gbp: 0, lkr: 0 },
      { month: "2014", type: "medical", label: "Medical Services", location: "Sri Lanka", gbp: 0, lkr: 0 },
      { month: "2014", type: "water", label: "Tube Wells", location: "Sri Lanka", gbp: 0, lkr: 0 },
      { month: "2014", type: "disaster", label: "Disaster Relief", location: "Sri Lanka", gbp: 0, lkr: 300000 },
      { month: "2014", type: "religious", label: "Fitra", location: "Sri Lanka", gbp: 0, lkr: 703200 },
      { month: "2014", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 451000 },
    ],
  },
  {
    id: "y2015",
    label: "2015",
    projects: [
      { month: "Feb 2015", type: "housing", label: "Housing & Sanitation", location: "Ratmaliyaya", gbp: 0, lkr: 58000 },
      { month: "Apr 2015", type: "employment", label: "Employment Support", location: "Arafanagar", gbp: 0, lkr: 50000 },
      { month: "Jun 2015", type: "medical", label: "Medical & Health", location: "Colombo", gbp: 0, lkr: 50000 },
      { month: "Jun 2015", type: "medical", label: "Medical & Health", location: "Panandura", gbp: 0, lkr: 15000 },
      { month: "Jun 2015", type: "sports", label: "Sports", location: "Puttalam", gbp: 0, lkr: 500000 },
      { month: "Jul 2015", type: "employment", label: "Employment Support", location: "Thillayadi", gbp: 0, lkr: 50000 },
      { month: "Jul 2015", type: "religious", label: "Fitra", location: "Sri Lanka", gbp: 0, lkr: 662500 },
      { month: "Aug 2015", type: "medical", label: "Medical & Health", location: "Negombo", gbp: 0, lkr: 50000 },
      { month: "Aug 2015", type: "education", label: "Education Support", location: "Nuracholai", gbp: 0, lkr: 50000 },
      { month: "Aug 2015", type: "welfare", label: "Family Support", location: "Sri Lanka", gbp: 0, lkr: 185000 },
      { month: "Aug 2015", type: "employment", label: "Employment Support", location: "Sri Lanka", gbp: 0, lkr: 182500 },
      { month: "Sep 2015", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 451000 },
      { month: "Sep 2015", type: "disability", label: "Wheelchair", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "Oct 2015", type: "medical", label: "Medical & Health", location: "Panandura", gbp: 0, lkr: 35000 },
      { month: "Oct 2015", type: "employment", label: "Employment Support", location: "Nuraicholai", gbp: 0, lkr: 50000 },
      { month: "Oct 2015", type: "housing", label: "Housing & Sanitation", location: "Jaffna", gbp: 0, lkr: 25000 },
      { month: "Nov 2015", type: "education", label: "Education Support", location: "Alankuda", gbp: 0, lkr: 36000 },
      { month: "Nov 2015", type: "admin", label: "Eid Gathering", location: "East London, UK", gbp: 2352.50, lkr: 0 },
    ],
  },
  {
    id: "y2016",
    label: "2016",
    projects: [
      { month: "Jan 2016", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 15000 },
      { month: "Mar 2016", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "Mar 2016", type: "employment", label: "Employment Support", location: "Sri Lanka", gbp: 0, lkr: 10000 },
      { month: "Mar 2016", type: "welfare", label: "Family Support", location: "Sri Lanka", gbp: 0, lkr: 30000 },
      { month: "May 2016", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 30000 },
      { month: "Jun 2016", type: "housing", label: "Housing & Sanitation", location: "Sri Lanka", gbp: 0, lkr: 349000 },
      { month: "Jun 2016", type: "sports", label: "Sports", location: "Sri Lanka", gbp: 0, lkr: 210000 },
      { month: "Jun 2016", type: "religious", label: "Fitra", location: "Sri Lanka", gbp: 0, lkr: 1112020 },
      { month: "Jun 2016", type: "religious", label: "Ifthar", location: "Sri Lanka / London", gbp: 0, lkr: 70000 },
      { month: "Jun 2016", type: "religious", label: "Zakath", location: "UK", gbp: 150, lkr: 0 },
      { month: "Jul 2016", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 25000 },
      { month: "Jul 2016", type: "welfare", label: "Orphans & Elders", location: "Sri Lanka", gbp: 0, lkr: 100000 },
      { month: "Jul 2016", type: "disability", label: "Wheelchair", location: "Sri Lanka", gbp: 0, lkr: 40000 },
      { month: "Jul 2016", type: "housing", label: "Housing & Sanitation", location: "Sri Lanka", gbp: 0, lkr: 110000 },
      { month: "Aug 2016", type: "employment", label: "Employment Support", location: "Negombo", gbp: 0, lkr: 177000 },
      { month: "Aug 2016", type: "housing", label: "Housing & Sanitation", location: "Sri Lanka", gbp: 0, lkr: 200000 },
      { month: "Aug 2016", type: "disaster", label: "Emergency Disaster", location: "Sri Lanka", gbp: 0, lkr: 1428000 },
      { month: "Sep 2016", type: "employment", label: "Employment Support", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "Sep 2016", type: "disability", label: "Disability Support", location: "Sri Lanka", gbp: 0, lkr: 40000 },
      { month: "Sep 2016", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 517500 },
      { month: "Sep 2016", type: "admin", label: "Eid Gathering", location: "UK", gbp: 3311, lkr: 0 },
      { month: "Dec 2016", type: "housing", label: "Housing & Sanitation", location: "Sri Lanka", gbp: 0, lkr: 110000 },
      { month: "Dec 2016", type: "employment", label: "Employment Support", location: "Sri Lanka", gbp: 0, lkr: 73000 },
    ],
  },
  {
    id: "y2017",
    label: "2017",
    projects: [
      { month: "Mar 2017", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "Mar 2017", type: "employment", label: "Employment Support", location: "Sri Lanka", gbp: 0, lkr: 45000 },
      { month: "Apr 2017", type: "education", label: "Education Support", location: "Puttalam", gbp: 0, lkr: 15000 },
      { month: "May 2017", type: "medical", label: "Medical & Health", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "Jun 2017", type: "religious", label: "Fitra", location: "Sri Lanka", gbp: 0, lkr: 644605 },
      { month: "Jul 2017", type: "medical", label: "Medical & Health", location: "Trincomalee", gbp: 0, lkr: 30000 },
      { month: "Jul 2017", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 20000 },
      { month: "Aug 2017", type: "medical", label: "Medical & Health", location: "Jaffna", gbp: 0, lkr: 80000 },
      { month: "Aug 2017", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 40000 },
      { month: "Aug 2017", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 40000 },
      { month: "Aug 2017", type: "education", label: "Education (School Build)", location: "Jaffna", gbp: 0, lkr: 500000 },
      { month: "Aug 2017", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 129000 },
      { month: "Aug 2017", type: "employment", label: "Employment Support", location: "Kilinochchi", gbp: 0, lkr: 40000 },
      { month: "Aug 2017", type: "housing", label: "Housing & Sanitation", location: "Jaffna", gbp: 0, lkr: 150000 },
      { month: "Aug 2017", type: "housing", label: "Housing & Sanitation", location: "Jaffna", gbp: 0, lkr: 25000 },
      { month: "Aug 2017", type: "sports", label: "Sports", location: "Puttalam", gbp: 0, lkr: 150000 },
      { month: "Aug 2017", type: "welfare", label: "Family Support", location: "Negombo", gbp: 0, lkr: 70000 },
      { month: "Aug 2017", type: "disaster", label: "Emergency Disaster", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "Aug 2017", type: "welfare", label: "Orphans & Elders", location: "Jaffna", gbp: 0, lkr: 50000 },
      { month: "Aug 2017", type: "admin", label: "Coconut Tree Maintenance", location: "Jaffna", gbp: 0, lkr: 75000 },
      { month: "Aug 2017", type: "employment", label: "Employment Support", location: "Jaffna", gbp: 0, lkr: 50000 },
      { month: "Aug 2017", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 229320 },
      { month: "Aug 2017", type: "water", label: "Tube Well", location: "Mullaithivu", gbp: 0, lkr: 70000 },
      { month: "Aug 2017", type: "water", label: "Tube Well", location: "Trincomalee", gbp: 0, lkr: 284520 },
      { month: "Aug 2017", type: "water", label: "Tube Well", location: "Mullaithivu", gbp: 0, lkr: 70000 },
      { month: "Aug 2017", type: "water", label: "Tube Well", location: "Mullaiyaveli", gbp: 0, lkr: 70000 },
      { month: "Aug 2017", type: "water", label: "Tube Well", location: "Mullaithivu", gbp: 0, lkr: 70000 },
      { month: "Aug 2017", type: "water", label: "Tube Well", location: "Mullaiveli", gbp: 0, lkr: 70000 },
      { month: "Aug 2017", type: "water", label: "Tube Well", location: "Jaffna", gbp: 0, lkr: 70000 },
      { month: "Sep 2017", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 15000 },
      { month: "Sep 2017", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 70000 },
      { month: "Sep 2017", type: "housing", label: "Housing & Sanitation", location: "Puttalam", gbp: 0, lkr: 100000 },
      { month: "Sep 2017", type: "housing", label: "Housing & Sanitation", location: "Panandura", gbp: 0, lkr: 50000 },
      { month: "Sep 2017", type: "welfare", label: "Family Support", location: "Sri Lanka", gbp: 0, lkr: 100000 },
      { month: "Oct 2017", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 90000 },
      { month: "Oct 2017", type: "education", label: "Education Support", location: "Nuracholai", gbp: 0, lkr: 90000 },
      { month: "Oct 2017", type: "water", label: "Tube Well", location: "Jaffna", gbp: 0, lkr: 70000 },
      { month: "Oct 2017", type: "water", label: "Tube Well", location: "Jaffna", gbp: 0, lkr: 70000 },
      { month: "Oct 2017", type: "disability", label: "Wheelchair", location: "Puttalam", gbp: 0, lkr: 70000 },
    ],
  },
  {
    id: "y2018",
    label: "2018",
    projects: [
      { month: "Jan 2018", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 45000 },
      { month: "Jan 2018", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 20000 },
      { month: "Feb 2018", type: "employment", label: "Employment Support", location: "Ratmaliyaya, Puttalam", gbp: 0, lkr: 25000 },
      { month: "Feb 2018", type: "housing", label: "Housing & Sanitation", location: "Sri Lanka", gbp: 0, lkr: 20000 },
      { month: "Feb 2018", type: "housing", label: "Housing & Sanitation", location: "Mankumban, Jaffna", gbp: 0, lkr: 20000 },
      { month: "Feb 2018", type: "housing", label: "Housing & Sanitation", location: "Mankumban, Jaffna", gbp: 0, lkr: 20000 },
      { month: "Feb 2018", type: "housing", label: "Housing & Sanitation", location: "Paalavi Camp, Puttalam", gbp: 0, lkr: 98000 },
      { month: "Feb 2018", type: "housing", label: "Housing & Sanitation", location: "Mankumban, Jaffna", gbp: 0, lkr: 20000 },
      { month: "Feb 2018", type: "housing", label: "Housing & Sanitation", location: "Mankumban, Jaffna", gbp: 0, lkr: 20000 },
      { month: "Mar 2018", type: "education", label: "Education Support", location: "Jaffna", gbp: 0, lkr: 15000 },
      { month: "May 2018", type: "employment", label: "Employment Support", location: "Sadamiyapuram, Puttalam", gbp: 0, lkr: 100000 },
      { month: "May 2018", type: "housing", label: "Housing & Sanitation", location: "Thillayadi, Puttalam", gbp: 0, lkr: 100000 },
      { month: "May 2018", type: "housing", label: "Housing & Sanitation", location: "Jaffna", gbp: 0, lkr: 153000 },
      { month: "May 2018", type: "water", label: "Tube Well", location: "Mankumban, Jaffna", gbp: 0, lkr: 15000 },
      { month: "Jun 2018", type: "religious", label: "Fitra", location: "Sri Lanka", gbp: 0, lkr: 788000 },
      { month: "Jun 2018", type: "religious", label: "Ifthar", location: "Sri Lanka", gbp: 0, lkr: 731000 },
      { month: "Jun 2018", type: "religious", label: "Zakath", location: "Sri Lanka", gbp: 0, lkr: 400000 },
      { month: "Jul 2018", type: "water", label: "Tube Well", location: "Hijrapuram, Mullaithivu", gbp: 0, lkr: 80000 },
      { month: "Jul 2018", type: "water", label: "Tube Well", location: "Mankumban, Jaffna", gbp: 0, lkr: 80000 },
      { month: "Jul 2018", type: "water", label: "Tube Well", location: "Kamal Road, Jaffna", gbp: 0, lkr: 80000 },
      { month: "Jul 2018", type: "water", label: "Tube Well", location: "Aasath Road, Jaffna", gbp: 0, lkr: 80000 },
      { month: "Jul 2018", type: "water", label: "Tube Well", location: "Sadamiyapuram, Puttalam", gbp: 0, lkr: 80000 },
      { month: "Aug 2018", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 375000 },
      { month: "Aug 2018", type: "water", label: "Tube Well", location: "Jaffna", gbp: 0, lkr: 125000 },
      { month: "Nov 2018", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 150000 },
    ],
  },
  {
    id: "y2019",
    label: "2019",
    projects: [
      { month: "Jan 2019", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 235000 },
      { month: "Jan 2019", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 47000 },
      { month: "Jan 2019", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 25000 },
      { month: "Feb 2019", type: "water", label: "Tube Well", location: "Chavakacheri", gbp: 0, lkr: 98000 },
      { month: "Feb 2019", type: "water", label: "Tube Well", location: "Jaffna", gbp: 0, lkr: 110000 },
      { month: "Feb 2019", type: "water", label: "Tube Well", location: "Mullaithivu", gbp: 0, lkr: 110000 },
      { month: "Feb 2019", type: "water", label: "Tube Well", location: "Mullaithivu", gbp: 0, lkr: 102000 },
      { month: "Mar 2019", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 25000 },
      { month: "Mar 2019", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 150000 },
      { month: "Mar 2019", type: "water", label: "Tube Well", location: "Mullaithivu", gbp: 0, lkr: 135000 },
      { month: "Mar 2019", type: "water", label: "Tube Well", location: "Jaffna", gbp: 0, lkr: 115000 },
      { month: "Mar 2019", type: "housing", label: "Housing & Sanitation", location: "Wattrapola, Panandura", gbp: 0, lkr: 50000 },
      { month: "Mar 2019", type: "employment", label: "Employment Support", location: "Panandura", gbp: 0, lkr: 45000 },
      { month: "May 2019", type: "religious", label: "Fitra", location: "Sri Lanka", gbp: 0, lkr: 773000 },
      { month: "May 2019", type: "religious", label: "Ifthar", location: "Sri Lanka", gbp: 0, lkr: 508600 },
      { month: "Aug 2019", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 15000 },
      { month: "Aug 2019", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 174250 },
      { month: "Sep 2019", type: "education", label: "Education Support (Iggrikollawa)", location: "Sri Lanka", gbp: 0, lkr: 150000 },
      { month: "Sep 2019", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 45000 },
      { month: "Sep 2019", type: "water", label: "Tube Well", location: "Mullaithivu", gbp: 0, lkr: 125000 },
      { month: "Nov 2019", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 102000 },
      { month: "Dec 2019", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "Dec 2019", type: "education", label: "Education Support", location: "Sri Lanka", gbp: 0, lkr: 40000 },
      { month: "Dec 2019", type: "water", label: "Tube Well", location: "Jaffna", gbp: 0, lkr: 204000 },
      { month: "Dec 2019", type: "housing", label: "Housing & Sanitation", location: "Ratmaliyaya, Puttalam", gbp: 0, lkr: 208000 },
      { month: "Dec 2019", type: "housing", label: "Housing & Sanitation", location: "Panandura", gbp: 0, lkr: 18000 },
      { month: "Dec 2019", type: "sports", label: "Sports", location: "Thillayadi, Puttalam", gbp: 0, lkr: 62000 },
      { month: "Dec 2019", type: "water", label: "Water Supply", location: "Mankumban", gbp: 0, lkr: 15000 },
      { month: "2019", type: "welfare", label: "Transport Support", location: "Sri Lanka", gbp: 0, lkr: 50000 },
    ],
  },
  {
    id: "y2020",
    label: "2020",
    projects: [
      { month: "Jan 2020", type: "water", label: "Katheeja College Water Supply", location: "Jaffna", gbp: 0, lkr: 27500 },
      { month: "Jan 2020", type: "education", label: "Education Tuition Fees", location: "Jaffna", gbp: 0, lkr: 60000 },
      { month: "Feb 2020", type: "employment", label: "Employment (Cloth Business)", location: "Panandura", gbp: 0, lkr: 100000 },
      { month: "Feb 2020", type: "employment", label: "Employment (Short Eat Business)", location: "Alankuda", gbp: 0, lkr: 125000 },
      { month: "Feb 2020", type: "housing", label: "Al Aqsa Masjid Toilet Facilities", location: "Puttalam", gbp: 0, lkr: 200000 },
      { month: "Feb 2020", type: "housing", label: "House Rent (Cancer Patient)", location: "Puttalam", gbp: 0, lkr: 175000 },
      { month: "Mar 2020", type: "admin", label: "Katheeja College Garden Tools", location: "Jaffna", gbp: 0, lkr: 60000 },
      { month: "Mar 2020", type: "education", label: "Madrasa Roof", location: "Iggrikollawa", gbp: 0, lkr: 155000 },
      { month: "Mar 2020", type: "education", label: "Student Support", location: "Iggrikollawa", gbp: 0, lkr: 25000 },
      { month: "Mar 2020", type: "water", label: "Katheeja College Pipeline", location: "Jaffna", gbp: 0, lkr: 195000 },
      { month: "Mar 2020", type: "employment", label: "Business Support", location: "Jaffna", gbp: 0, lkr: 200000 },
      { month: "Mar 2020", type: "admin", label: "Coconut Tree Maintenance", location: "Mankumban", gbp: 0, lkr: 130000 },
      { month: "May 2020", type: "disaster", label: "COVID-19 Emergency Relief", location: "Sri Lanka", gbp: 0, lkr: 1414500 },
      { month: "May 2020", type: "disaster", label: "COVID-19 Relief", location: "Gambia, Africa", gbp: 500, lkr: 0 },
      { month: "May 2020", type: "disaster", label: "Olive Tree Project", location: "Gaza, Palestine", gbp: 280, lkr: 0 },
      { month: "Jun 2020", type: "disability", label: "Disabled Person Support", location: "Alankuda, Puttalam", gbp: 0, lkr: 45500 },
      { month: "Jun 2020", type: "disability", label: "Wheelchair", location: "Alankuda, Puttalam", gbp: 0, lkr: 22000 },
      { month: "Jun 2020", type: "housing", label: "Roof for House", location: "Alankuda, Puttalam", gbp: 0, lkr: 24000 },
      { month: "Jun 2020", type: "employment", label: "Small Business Support", location: "Kalmunaikudi", gbp: 0, lkr: 31500 },
      { month: "Jun 2020", type: "housing", label: "Water Tank", location: "Nuracholai", gbp: 0, lkr: 39000 },
      { month: "Jun 2020", type: "welfare", label: "Family Support", location: "Kamal Road, Jaffna", gbp: 0, lkr: 25000 },
      { month: "Jun 2020", type: "religious", label: "Fitra", location: "Sri Lanka", gbp: 0, lkr: 680450 },
      { month: "Jun 2020", type: "water", label: "Tube Well", location: "Hijrapuram, Mullaithivu", gbp: 0, lkr: 170000 },
      { month: "Jun 2020", type: "disability", label: "Push Chair (Disabled Person)", location: "Puttalam", gbp: 0, lkr: 19000 },
      { month: "Jun 2020", type: "religious", label: "Zakath", location: "Sri Lanka", gbp: 0, lkr: 531040 },
      { month: "Jun 2020", type: "religious", label: "Sadaqa", location: "Sri Lanka", gbp: 0, lkr: 184000 },
      { month: "Jul 2020", type: "housing", label: "WC for Bathroom", location: "Puttalam", gbp: 0, lkr: 58000 },
      { month: "Aug 2020", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 916300 },
      { month: "Aug 2020", type: "medical", label: "Medical (Kidney Operation)", location: "Sri Lanka", gbp: 0, lkr: 50000 },
      { month: "Oct 2020", type: "education", label: "Tuition Fees (Monthly)", location: "Jaffna", gbp: 0, lkr: 7000 },
      { month: "Oct 2020", type: "education", label: "Aalimah Course (3 Months)", location: "Madampe", gbp: 0, lkr: 30000 },
      { month: "Oct 2020", type: "housing", label: "House Build (Partial)", location: "Jaffna", gbp: 0, lkr: 60000 },
      { month: "Oct 2020", type: "employment", label: "Popcorn Machine (Business)", location: "Ilanthimoddy", gbp: 0, lkr: 40000 },
      { month: "Oct 2020", type: "disability", label: "Bed Set for Disabled Person", location: "Nuraicholai", gbp: 0, lkr: 16000 },
      { month: "Oct 2020", type: "employment", label: "Bicycle (Self-employment)", location: "Nuraicholai", gbp: 0, lkr: 22000 },
      { month: "Oct 2020", type: "disaster", label: "Emergency Food Parcels", location: "Puttalam", gbp: 0, lkr: 38500 },
      { month: "Oct 2020", type: "disaster", label: "Emergency Rice Bags", location: "Puttalam", gbp: 0, lkr: 125000 },
      { month: "Oct 2020", type: "water", label: "Tube Well (Common Use)", location: "Nachchikuda", gbp: 0, lkr: 180000 },
      { month: "Dec 2020", type: "water", label: "Tube Well (Common Use)", location: "Nachchikuda", gbp: 0, lkr: 150060 },
      { month: "Dec 2020", type: "housing", label: "Hut for Madrasa", location: "Puttalam", gbp: 0, lkr: 72000 },
      { month: "Dec 2020", type: "water", label: "Tube Well (Common Use)", location: "Nachchikuda", gbp: 0, lkr: 190000 },
      { month: "Dec 2020", type: "welfare", label: "Breakfast Programme", location: "Nachchikuda", gbp: 0, lkr: 12000 },
      { month: "Dec 2020", type: "disaster", label: "COVID-19 (1,000 Rice Bags)", location: "Negombo & Area", gbp: 0, lkr: 690000 },
      { month: "Dec 2020", type: "disaster", label: "Flood Appeal (157 Families)", location: "Jaffna Moor Street", gbp: 0, lkr: 392500 },
      { month: "Dec 2020", type: "water", label: "Tube Well (Kamal Lane)", location: "Jaffna", gbp: 0, lkr: 95000 },
      { month: "Dec 2020", type: "water", label: "Tube Well (Muslim College Road)", location: "Jaffna Moor Street", gbp: 0, lkr: 157200 },
    ],
  },
  {
    id: "y2021",
    label: "2021",
    projects: [
      { month: "Feb 2021", type: "medical", label: "Medical Support (Partial)", location: "Mawanella", gbp: 0, lkr: 145000 },
      { month: "Feb 2021", type: "disaster", label: "COVID-19 Rice Bags (113 Families)", location: "Kattankudy", gbp: 0, lkr: 68000 },
      { month: "Mar 2021", type: "medical", label: "Medical Support (Partial)", location: "Puttalam", gbp: 0, lkr: 218125 },
      { month: "Mar 2021", type: "water", label: "Tube Well (Common Use)", location: "Koiyavadi, Ettalai", gbp: 0, lkr: 170000 },
      { month: "Apr 2021", type: "water", label: "Tube Well (Common Use)", location: "Alankuda / Puttalam", gbp: 0, lkr: 185000 },
      { month: "Apr 2021", type: "employment", label: "Fishing Nets (Self Employment)", location: "Mankumban, Jaffna", gbp: 0, lkr: 53000 },
      { month: "May 2021", type: "water", label: "Tube Well (Common Use)", location: "Nachchikuda", gbp: 0, lkr: 185000 },
      { month: "May 2021", type: "education", label: "Madrasathun Nooraniya Donation", location: "Alankuda Eatalai", gbp: 0, lkr: 53000 },
      { month: "May 2021", type: "religious", label: "Fitra Distribution (20 Locations)", location: "Sri Lanka", gbp: 0, lkr: 1283500 },
      { month: "May 2021", type: "education", label: "Al Hikmah School (Collection)", location: "Luton, UK", gbp: 1200, lkr: 0 },
      { month: "May 2021", type: "religious", label: "Ifthar (Ramadhan)", location: "Various, Sri Lanka", gbp: 0, lkr: 742500 },
      { month: "Jun 2021", type: "disaster", label: "Flood Relief", location: "Ratmaliyaya, Puttalam", gbp: 0, lkr: 150000 },
      { month: "Jun 2021", type: "disaster", label: "Flood Relief", location: "YMMA Nagar, Ratmaliyaya", gbp: 0, lkr: 120000 },
      { month: "Jul 2021", type: "religious", label: "Qurbani", location: "Various, Sri Lanka", gbp: 0, lkr: 895950 },
      { month: "Jul 2021", type: "admin", label: "SLMCC Fund Raising", location: "UK", gbp: 2030, lkr: 0 },
      { month: "Oct 2021", type: "housing", label: "Housing (Partial Support)", location: "Puttalam", gbp: 0, lkr: 100000 },
      { month: "Nov 2021", type: "water", label: "Water Tank", location: "Pommeiveli, Jaffna", gbp: 0, lkr: 54000 },
      { month: "Nov 2021", type: "disaster", label: "Flood Appeal Phase 1", location: "Puttalam (Palavi, Al-Jidda)", gbp: 0, lkr: 485250 },
      { month: "Nov 2021", type: "disaster", label: "Flood Appeal Phase 2", location: "Puttalam (Palavi, YMMA etc.)", gbp: 0, lkr: 1119750 },
      { month: "Dec 2021", type: "medical", label: "Medical (Kidney Transplant)", location: "Puttalam", gbp: 0, lkr: 100000 },
      { month: "Dec 2021", type: "medical", label: "Medical (Heart Surgery)", location: "Puttalam", gbp: 0, lkr: 50000 },
      { month: "Dec 2021", type: "medical", label: "Medical (Heart Surgery)", location: "Puttalam", gbp: 0, lkr: 50000 },
    ],
  },
  {
    id: "y2022",
    label: "2022",
    projects: [
      { month: "Mar 2022", type: "water", label: "Tube Well (Common Use)", location: "Mullaiyoor, Nuraicholai", gbp: 0, lkr: 255000 },
      { month: "Mar 2022", type: "water", label: "Tube Well (Common Use)", location: "Alankuda, Eatalai", gbp: 0, lkr: 255000 },
      { month: "Apr 2022", type: "religious", label: "Iftar – Gambia (ROCA)", location: "Gambia", gbp: 500, lkr: 0 },
      { month: "Apr 2022", type: "religious", label: "Iftar", location: "Various, Sri Lanka", gbp: 0, lkr: 1483500 },
      { month: "Apr 2022", type: "disaster", label: "Economic Crisis Relief Phase 1", location: "1,072 Families, Sri Lanka", gbp: 0, lkr: 1393600 },
      { month: "Apr 2022", type: "disaster", label: "Economic Crisis Relief Phase 2", location: "495 Families, Sri Lanka", gbp: 0, lkr: 639600 },
      { month: "Apr 2022", type: "religious", label: "Iftar Gathering", location: "East Ham, UK", gbp: 2089, lkr: 0 },
      { month: "May 2022", type: "religious", label: "Fitra (1,418 Parcels)", location: "Sri Lanka", gbp: 0, lkr: 1863200 },
      { month: "May 2022", type: "disaster", label: "Economic Crisis Relief Phase 3", location: "420 Families, Sri Lanka", gbp: 0, lkr: 546000 },
      { month: "May 2022", type: "disaster", label: "Economic Crisis Relief Phase 4", location: "348 Families, Sri Lanka", gbp: 0, lkr: 448500 },
      { month: "Jun 2022", type: "disaster", label: "Economic Crisis Relief Phase 5", location: "285 Families, Sri Lanka", gbp: 0, lkr: 370500 },
      { month: "Jun 2022", type: "disaster", label: "Economic Crisis Relief Phase 6", location: "443 Families, Sri Lanka", gbp: 0, lkr: 575900 },
      { month: "Jun 2022", type: "disaster", label: "Economic Crisis Relief Phase 7", location: "415 Families, Sri Lanka", gbp: 0, lkr: 539000 },
      { month: "Jun 2022", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 863790 },
      { month: "Jul 2022", type: "religious", label: "Zakath", location: "Sri Lanka", gbp: 0, lkr: 717000 },
      { month: "Oct 2022", type: "admin", label: "JMA Annual Gathering 2022", location: "UK", gbp: 8824.19, lkr: 0 },
      { month: "Dec 2022", type: "education", label: "Osmania College – Wall Build", location: "Sri Lanka", gbp: 0, lkr: 160000 },
      { month: "Dec 2022", type: "education", label: "Education Tuition Fees", location: "Sri Lanka", gbp: 0, lkr: 120000 },
      { month: "Dec 2022", type: "education", label: "Nursery Wall Painting", location: "Sri Lanka", gbp: 0, lkr: 20000 },
    ],
  },
  {
    id: "y2023",
    label: "2023",
    projects: [
      { month: "Jan 2023", type: "education", label: "Student Support", location: "Negombo", gbp: 0, lkr: 144000 },
      { month: "Feb 2023", type: "sports", label: "City Boys Club (YMMA Puttalam)", location: "Puttalam", gbp: 0, lkr: 48000 },
      { month: "Feb 2023", type: "education", label: "A-Level Student Support", location: "Puttalam", gbp: 0, lkr: 60000 },
      { month: "Feb 2023", type: "education", label: "A-Level Student Support", location: "Puttalam", gbp: 0, lkr: 15000 },
      { month: "Feb 2023", type: "education", label: "A-Level Student Support", location: "Puttalam", gbp: 0, lkr: 15000 },
      { month: "Feb 2023", type: "education", label: "University Students (3 Scholars)", location: "Puttalam", gbp: 0, lkr: 540000 },
      { month: "Feb 2023", type: "education", label: "Zahira College Group (96 Students)", location: "Colombo", gbp: 0, lkr: 50000 },
      { month: "Feb 2023", type: "disability", label: "Disabled Child Support", location: "Puttalam", gbp: 0, lkr: 36000 },
      { month: "Feb 2023", type: "medical", label: "Cancer Patient Assistance", location: "Puttalam", gbp: 0, lkr: 36000 },
      { month: "Feb 2023", type: "disaster", label: "Turkey & Syria Earthquake Relief", location: "Turkey / Syria", gbp: 1000, lkr: 0 },
      { month: "Apr 2023", type: "religious", label: "Iftar Gathering", location: "East Ham, UK", gbp: 1338.12, lkr: 0 },
      { month: "Apr 2023", type: "religious", label: "Iftar Gathering", location: "Leicester, UK", gbp: 810, lkr: 0 },
      { month: "Apr 2023", type: "religious", label: "Iftar Meals", location: "Various, Sri Lanka", gbp: 0, lkr: 871790 },
      { month: "Apr 2023", type: "religious", label: "Iftar Meals", location: "Various, Sri Lanka", gbp: 0, lkr: 137800 },
      { month: "Apr 2023", type: "religious", label: "Iftar Meals – Gambia", location: "Gambia", gbp: 700, lkr: 0 },
      { month: "Apr 2023", type: "religious", label: "Fitra Distribution", location: "Sri Lanka", gbp: 0, lkr: 2548125 },
      { month: "Apr 2023", type: "religious", label: "Zakat Assistance (6 People)", location: "Sri Lanka", gbp: 0, lkr: 515000 },
      { month: "Apr 2023", type: "housing", label: "House Build", location: "Puttalam", gbp: 0, lkr: 674491 },
      { month: "Jun 2023", type: "religious", label: "Qurbani", location: "Sri Lanka", gbp: 0, lkr: 1070250 },
      { month: "Jun 2023", type: "disability", label: "Disabled Children Support", location: "Kattankudy / Batticaloa", gbp: 0, lkr: 235000 },
      { month: "Jun 2023", type: "disability", label: "Disabled Mother Support", location: "Puttalam", gbp: 0, lkr: 35000 },
      { month: "Jul 2023", type: "welfare", label: "Revert Muslim Assistance", location: "Puttalam", gbp: 0, lkr: 261400 },
      { month: "Aug 2023", type: "welfare", label: "Revert Muslim Assistance", location: "Puttalam", gbp: 0, lkr: 172500 },
      { month: "Aug 2023", type: "disability", label: "School Support (Disabled Children)", location: "Sri Lanka", gbp: 0, lkr: 194000 },
      { month: "Aug 2023", type: "disability", label: "School Support (Disabled Children)", location: "Sri Lanka", gbp: 0, lkr: 212000 },
    ],
  },
];

export const CATEGORY_CONFIG: Record<
  ProjectCategory,
  { label: string; textColor: string; bgColor: string }
> = {
  education: { label: "Education", textColor: "#0D5C6B", bgColor: "#E0F2EF" },
  medical: { label: "Medical", textColor: "#2962CC", bgColor: "#E8F0FE" },
  housing: { label: "Housing", textColor: "#B45309", bgColor: "#FEF3C7" },
  employment: { label: "Employment", textColor: "#6D28D9", bgColor: "#EDE9FE" },
  water: { label: "Water / Well", textColor: "#065F46", bgColor: "#D1FAE5" },
  religious: { label: "Fitra / Qurbani", textColor: "#92400E", bgColor: "#FEF3C7" },
  disaster: { label: "Emergency Relief", textColor: "#991B1B", bgColor: "#FEE2E2" },
  sports: { label: "Sports", textColor: "#166534", bgColor: "#DCFCE7" },
  welfare: { label: "Family / Welfare", textColor: "#9D174D", bgColor: "#FCE7F3" },
  disability: { label: "Disability", textColor: "#3730A3", bgColor: "#E0E7FF" },
  admin: { label: "Admin / Event", textColor: "#374151", bgColor: "#F3F4F6" },
};

export const FILTER_CATEGORIES: { key: ProjectCategory | "all"; label: string }[] = [
  { key: "all", label: "All" },
  { key: "education", label: "Education" },
  { key: "medical", label: "Medical" },
  { key: "housing", label: "Housing" },
  { key: "employment", label: "Employment" },
  { key: "water", label: "Water / Wells" },
  { key: "religious", label: "Fitra / Qurbani" },
  { key: "disaster", label: "Emergency Relief" },
  { key: "disability", label: "Disability" },
  { key: "welfare", label: "Family / Welfare" },
  { key: "sports", label: "Sports" },
];

export function computeStats(years: YearGroup[]) {
  let totalProjects = 0;
  let totalGBP = 0;
  let totalLKR = 0;
  const locations = new Set<string>();

  for (const yr of years) {
    for (const p of yr.projects) {
      totalProjects++;
      totalGBP += p.gbp;
      totalLKR += p.lkr;
      if (p.location) locations.add(p.location.split(",")[0].trim());
    }
  }

  return { totalProjects, totalGBP, totalLKR, uniqueLocations: locations.size };
}